name: 'Ecommerce_Pipeline'
version: '1.0.0'
config-version: 2

profile: 'Ecommerce_Pipeline'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Ecommerce_Pipeline:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    analytics:
      +schema: analytics
      +materialized: table